### ISSUE TITLE
error with import inside declared module

### ISSUE THREAD

**Issue by cocodrino** [sjrd/scala-js-ts-importer#12]
Hi..sorry but I'm trying convert the atom.d.ts from definitelytyped

when I run the importer I get an error in the line 1263:

```
  Parse error at 1263.2
  ``}'' expected but `import' found
     import spacePen = require("space-pen");

      ^
```

seems than to the importer doesnt like that import clause inside a module declaration...this is the code

```
  declare var atom:AtomCore.IAtom;

  declare module "atom" {
     import spacePen = require("space-pen"); // <----here is the problem!!

     var $:typeof spacePen.$; 
```

I'm not so much familiar with typescript and I don't know how fix it by hand..can you give me a clue??..thanks

**Comment by DanielJoyce** [comment]
Looks like a type alias to me.
