### ISSUE TITLE
Importing react.d.ts

### ISSUE THREAD

**Issue by mfirry** [sjrd/scala-js-ts-importer#21]
I get
```
Parse error at 11.5
``}'' expected but identifier type found
    type ReactType = ComponentClass<any> | string;

    ^
```
when importing https://raw.githubusercontent.com/borisyankov/DefinitelyTyped/master/react/react.d.ts

**Comment by sjrd** [comment]
Oi oi. I could probably be fix/support the `type` members (after all, Scala also has type members), but I'll never know what to do about the union type :-s I suggest you comment out/delete this line to import the file. If you're lucky, there aren't many like that, and you'll be able to fix up after the import. If you're not, well ... I don't know what to do.

**Comment by sjrd** [comment]
Type alias declarations are now supported in the latest master.
