### ISSUE TITLE
can't make it work

### ISSUE THREAD

**Issue by ndesmoul** [sjrd/scala-js-ts-importer#22]
I want to import typescript definition of the jsbn lib.
I downloaded the project (downloading the zip) and did:

sbt run jsbn.d.ts BigInteger.scala math

The 'jsbn.d.ts' file is at the project root.
It compiles without problem, but then I have an error :

[info] Running org.scalajs.tools.tsimporter.Main 
Usage: scalajs-ts-importer <input.d.ts> <output.scala> [<package>]
  <input.d.ts>     TypeScript type definition file to read
  <output.scala>   Output Scala.js file
  <package>        Package name for the output (defaults to "importedjs")
java.lang.RuntimeException: Nonzero exit code: 1
        at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code: 1
[error] Total time: 0 s, completed 17 févr. 2015 10:56:34

I don't have any idea of where the problem comes from. Actually doing a 'sbt run' without argument gives the same error.
Am I missing something?

**Comment by sjrd** [comment]
Oh, right. You need to quote everything:
```
$ sbt 'run jsbn.d.ts BigInteger.scala math'
```
I'll fix the readme.

**Comment by ndesmoul** [comment]
Indeed it works. Thanks a lot!
