### ISSUE TITLE
number[]|string[] type disjunction fails

### ISSUE THREAD

**Issue by cocodrino** [sjrd/scala-js-ts-importer#23]
Hi, I'm trying to convert https://github.com/photonstorm/phaser/blob/master/typescript/phaser.d.ts to scalajs but fails in the line 58

```scala
``)'' expected but ErrorToken(illegal character) found
        constructor(game: Phaser.Game, parent: Phaser.Sprite, name: string, frameData: Phaser.FrameData, frames: number[]|string[], frameRate?: number, loop?: boolean);


```

the reason is pretty clear, scalajs doesnt support this type number[]|string[]  ..not pretty sure but I think than it's named type disjunction no? :) .

how can handle it in scalajs?..thanks!!

**Comment by sjrd** [comment]
The recommended strategy is to turn these into several overloads of the method. One taking a `number[]` aka `js.Array[Double]`, and one taking a `string[]` aka `js.Array[String]`.

**Comment by ademartini** [comment]
There are also properties that have two possible types.  Maybe using Either would make sense.

**Comment by sjrd** [comment]
Using `Either` would not make sense, no. However the upcoming `js.|` will be perfect. (See https://github.com/scala-js/scala-js/pull/1826)

**Comment by cocodrino** [comment]
this script is really great

https://github.com/GenslerAppsPod/scalavro/blob/master/util/src/main/scala/com/gensler/scalavro/util/union.scala

https://github.com/GenslerAppsPod/scalavro/blob/master/util/src/test/scala/com/gensler/scalavro/util/UnionSpec.scala

I replace the typescript union types with a type StringOrInt for instance, then I include the definition in the scala file and works great (it's really tricky although can be automatized), unfortunately I'm not using scalajs right now (but I love it) but this works ok for me, not sure but I think than the upcoming scala version will include union types, I remember seeing it in a slide

**Comment by sixman9** [comment]
Adding to @cocodrino, I also want to parse the [phaser.d.ts][phaser-TS] file, to ScalaJS. 

I'd like to offer my 2 cents regarding the possible integration of Typescript's [union types][ts-union] into Scala[JS], I came across the following Stackoverflow posts, outlining the use of Scala's '[Either][scala-either]' parameter marker or creating a group of 'Type Disjunction' (Union) helper objects/classes.

[Using Scala's 'Either' for type selection][so-scala-either] 

or

[How to define “type disjunction” (union types) in Scala][so-scala-union]

The latter of these could be greatly aided by the use of Scala macros/[quasiquotes][quasiquotes] to create new, as-yet-unamed, object-class relationships/unions (or any new Scala code tree).

[Scala Macros/Quasiquotes][learn-quasiquotes]

Also of interest might be the ability to compile new Scala code at runtime, using the 'Toolbox' api:

[Just-in-time-scala-compilation][scala-compilation]

[learn-quasiquotes]: https://www.google.com/search?q=scala+quasiquotes+macros

[quasiquotes]: http://docs.scala-lang.org/overviews/quasiquotes/usecases.html

[scala-compilation]: http://docs.scala-lang.org/overviews/quasiquotes/usecases.html#just-in-time-compilation

[phaser-TS]: https://github.com/photonstorm/phaser/blob/master/typescript/phaser.d.ts

[ts-union]: https://www.google.com/search?q=typescript+union+types

[scala-either]: http://www.scala-lang.org/api/current/index.html#scala.util.Either

[so-scala-either]: http://stackoverflow.com/questions/9611012/accept-multiple-types-for-a-parameter-in-scala/9611145#9611145

[so-scala-union]: http://stackoverflow.com/questions/3508077/how-to-define-type-disjunction-union-types/3508555#3508555

**Comment by sjrd** [comment]
We now have [`A | B`](http://www.scala-js.org/api/scalajs-library/0.6.5/#scala.scalajs.js.$bar) in Scala.js. This is what should be used here.

**Comment by sixman9** [comment]
That's great, apologies for being so long-winded, I just thought it best to offer as much help as possible. Of course, Scala.js's [A | B](http://www.scala-js.org/api/scalajs-library/0.6.5/#scala.scalajs.js.%24bar) construct is infinitely more simple/elegant.

Any ideas on when you might integrate this into you importer, thanks?

**Comment by sjrd** [comment]
In the coming weeks. I'll be busy until end of September, but after that I'll start working a bit on this.

**Comment by sjrd** [comment]
I just implemented this in the latest master. It is now possible to import phaser.d.ts.
