### ISSUE TITLE
annotated package objects

### ISSUE THREAD

**Issue by joprice** [sjrd/scala-js-ts-importer#30]
The printer generates package objects with `@JSName` annotations:

https://github.com/sjrd/scala-js-ts-importer/blob/bce58cd7d191c2cf59ba1fd063592c409c5fa6b0/src/main/scala/org/scalajs/tools/tsimporter/sc/Printer.scala#L63

This has been identified elsewhere as a scala limitation:

https://github.com/scala-js/scala-js/issues/30

**Comment by sjrd** [comment]
Thanks for the report.

**Comment by joprice** [comment]
:+1:
