### ISSUE TITLE
Support missing for unions, intersections, and numeric enum entries

### ISSUE THREAD

**Issue by Dessix** [sjrd/scala-js-ts-importer#35]
I'm using this thread to record translation issues that have arisen since the introduction of Typescript 2(.1)'s changes, and can provide unit tests if requested.

Example of intersection and union usages:
```typescript
funcUnI<T>(objects: T[] | B[], opts?: C & {
    d?: object | number;
    e: number;
}): T;
```

Example of Enum with numeric entries:
```typescript
declare var EnumWithNums: {
    0: number;
    1: number;
    4: number;
};
```

**Comment by Dessix** [comment]
Also, properties of the form `x?: y` become translated as `x = ???`.

**Comment by Dessix** [comment]
Anonymous interfaces in parameter types are translated as "Any", rather than creating a purpose-built trait to preserve type strength.

**Comment by sjrd** [comment]
* Unions should be supported, IIRC
* Intersection could be implemented as `with`
* Optional properties should probably be translated as `= js.undefined` properties, since 0.6.14.
* There's probably something meaningful to do about enums with numeric values, indeed.
* Anonymous interfaces cannot be translated to a single-use trait, as that would use nominal typing instead of structural typing. Besides, the architecture of this implementation is not easily amenable to such transformations.

**Comment by andrelfpinto** [comment]
I am having problems with union types, too.

Running:

```
sbt 'run simple.ts Simple.scala'
```

With a file `simple.ts`:

```
interface A {}
interface B {}

class C extends A | B {}
```

I get:

```
Parse error at 4.19
'`{'' expected but `|' found
class C extends A | B {}
                  ^

Exception: sbt.TrapExitSecurityException thrown from the UncaughtExceptionHandler in thread "run-main-0"
[error] java.lang.RuntimeException: Nonzero exit code: 2
[error]         at sbt.Run$.executeTrapExit(Run.scala:124)
[error]         at sbt.Run.run(Run.scala:77)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$5(Defaults.scala:1168)
[error]         at sbt.Defaults$.$anonfun$bgRunTask$5$adapted(Defaults.scala:1163)
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error]         at java.lang.Thread.run(Thread.java:745)
[error] (Compile / run) Nonzero exit code: 2
[error] Total time: 2 s, completed 06/02/2018 10:37:56
```

**Comment by sjrd** [comment]
That's not valid TypeScript code. The extends clause must reference a [`ClassType`](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#8.1.1), which is a `TypeReference`, which [cannot be a union type](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a1-types).

Also, that makes sense, as I cannot imagine what the semantics of such an extend clause would be.

**Comment by andrelfpinto** [comment]
I am sorry for the wrong simplification (I am not a TypeScript guy). I think this one is valid:

```
class A {}
class B {}

function f<T extends A | B>(a: T) {
}
```

If it is so, it doesn't run either:

```
Parse error at 4.24
'`>'' expected but `|' found
function f<T extends A | B>(a: T) {
                       ^
```

**Comment by sjrd** [comment]
OK, that one seems meaningful. Please report it as a separate issue. The present issue is too much of a bag of stuff to be actionable.

**Comment by sjrd** [comment]
I'm going to close this issue because most (all) of what it reported has been fixed. If individual things don't work yet, they should be reported as individual issues.
