### ISSUE TITLE
parse default type parameters "type Foo<P = any>"

### ISSUE THREAD

**Issue by aappddeevv** [sjrd/scala-js-ts-importer#59]
It's probably safe to ignore them, but I received parse errors on:
```typescript
type ReactType<P = any> = string | ComponentType<P>;
```
Error:
```sh
Parse error at 74.22
'`>'' expected but `=' found
    type ReactType<P = any> = string | ComponentType<P>;
```

**Comment by sjrd** [comment]
Yes, they should be parsed and ignored.

**Comment by aappddeevv** [comment]
I'll look at it again, but the error suggested that it was failing at the parse. Or did you mean that "yes", it does need to parse that and it does not parse it currently?

**Comment by sjrd** [comment]
That's what I meant, indeed.
