### ISSUE TITLE
Inconsistent Discard of Specialized Signatures

### ISSUE THREAD

**Issue by bpholt** [sjrd/scala-js-ts-importer#63]
There is logic in `Importer.scala#L228-L230` to discard specialized signatures (i.e. literal types encoded as `ConstantType`), but it is applied inconsistently.

https://github.com/sjrd/scala-js-ts-importer/blob/d35da0cf55a39b8781d37f2cd6653285e6fcd343/src/main/scala/org/scalajs/tools/tsimporter/Importer.scala#L228-L230

So, a function defined as

```typescript
update(input: 0): void;
```

will be discarded, whereas function with a union type containing a `ConstantType` in one of its cases will not be discarded:

```typescript
update(input: 0 | 1): void;
```
results in
```scala
def update(input: Int): Unit = js.native
```

I'm not sure what motivates the original discard. Is it because the Scala `Int` type isn't an actual match for the TrueScript `0 | 1`? (If so, the discard logic should probably look deeper at `UnionType` instances.) If not, can someone elaborate as to why the function is discarded?

FWIW, there is a "workaround;" the function will be included in the Scala trait by defining in TypeScript

```typescript
update(input: 0 | 0): void;
```

but that seems like quite a hack to me.

**Comment by bpholt** [comment]
This may also apply to TypeScript exported types and their Scala type aliases:

```typescript
declare module numberlit {
  export type Zero = 0;
}
```

results in

```scala
type Zero = Int
```

which may be wrong? If function definitions are discarded because the types are not a perfect match, then maybe these type aliases should be too?

**Comment by sjrd** [comment]
This is problematic. We should always widen literal types to their "large" type (e.g., `0` -> `Int`). But then we need to prune duplicates that result from things like
```typescript
void foo(x: 1);
void foo(x: 2);
```
or
```typescript
void bar(x: "hello");
void bar(x: string);
```

**Comment by bpholt** [comment]
It seems like some deduplication is already happening for cases where the Scala signatures match exactly. If I comment out lines 229-230 and run the importer with this input:

```typescript
declare module duplicateliteraltypes {
    export interface duplicateliteraltypes {
        duplicate(input: true): void;
        duplicate(input: false): void;

        duplicate(input: 0): void;
        duplicate(input: 1): void;
    }
}
```

it outputs 

```scala
@js.native
trait duplicateliteraltypes extends js.Object {
  def duplicate(input: Boolean): Unit = js.native
  def duplicate(input: Int): Unit = js.native
}
```

which seems right?

But if the signatures otherwise vary (e.g. different return types), then it outputs all the methods. For example: 

```typescript
duplicate(input: 0): string;
duplicate(input: 1): void;
```

turns in to

```scala
def duplicate(input: Int): String = js.native
def duplicate(input: Int): Unit = js.native
```

I'm not sure how to resolve that.

**Comment by sjrd** [comment]
If the result types are different, then there is no good answer. The importer should just emit both signatures and let a human fix it afterwards.

**Comment by bpholt** [comment]
> If the result types are different, then there is no good answer. The importer should just emit both signatures and let a human fix it afterwards.

Ok, that's the current behavior with the early return commented out. I'll send a PR with those lines removed and my `duplicateliteraltypes` sample case.
