### ISSUE TITLE
Union type not accepted as upper bound of a generic type parameter

### ISSUE THREAD

**Issue by andrelfpinto** [sjrd/scala-js-ts-importer#66]
I am having problems with union types.

Running:

```
sbt 'run simple.ts Simple.scala'
```

With a file `simple.ts`:

```
interface A {}
interface B {}

function f<T extends A | B>(t: T) {
}
```

I get:

```
Parse error at 4.24
'`>'' expected but `|' found
function f<T extends A | B>(t: T) {
                       ^
```

**Comment by sjrd** [comment]
It seems that `typeRef` in [the definition of `typeParam`](https://github.com/sjrd/scala-js-ts-importer/blob/e47c9897e7dd0c0aeddccd5098d54fef60112459/src/main/scala/org/scalajs/tools/tsimporter/parser/TSDefParser.scala#L143) is too restrictive. It should probably be `typeDesc` instead.
