### ISSUE TITLE
Parse error with generic type parameter default values

### ISSUE THREAD

**Issue by bpholt** [sjrd/scala-js-ts-importer#72]
When importing the [AWS Lambda](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/aws-lambda) type definitions, I get a parser error on [this block of source](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/50dafbd8e340f232392f5d7b88d163a046ebfdd5/types/aws-lambda/index.d.ts#L539):

```typescript
export type Handler<TEvent = any, TResult = any> = (event: TEvent, context: Context, callback: Callback<TResult>) => void;
```

```
Parse error at 539.28
'`>'' expected but `=' found
export type Handler<TEvent = any, TResult = any> = (event: TEvent, context: Context, callback: Callback<TResult>) => void;
                           ^
```

[As of TypeScript 2.3](https://blog.mariusschulz.com/2017/06/02/typescript-2-3-generic-parameter-defaults) generic type parameters are allowed to have default values, so this should at least parse and discard the provided value.

**Comment by sjrd** [comment]
Duplicate of #59 ?

**Comment by bpholt** [comment]
Yes, sorry. I thought I searched for a matching issue but I must have missed it.
